on:
  schedule:
    - cron: '0 0,12 * * *'

jobs:
  update_csv:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: npm install --production
    - run: npm run update-csv
    - run: npm run collect-artifacts
