name: batch

on:
  schedule:
    - cron: '25 * * * *'

jobs:
  update_csv:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: npm install
    - run: npm run update-csv
    - uses: EndBug/add-and-commit@v7
      with:
        add: data
        branch: some-branch
        default_author: github_actions
